Metadata-check_metadata_attributes_exist:
  expected_attrs: [paired_end, has_ercc]

Raw Reads-check_for_outliers: &fastQC_outliers
  mqc_module: FastQC
  mqc_plot: general_stats
  mqc_keys:
    - percent_gc
    - avg_sequence_length
    - total_sequences
    - percent_duplicates
  thresholds:
    - code: YELLOW1
      stdev_threshold: 2
      middle_fcn: median
    - code: RED1
      stdev_threshold: 4
      middle_fcn: median

Trim Reads-check_for_outliers: *fastQC_outliers

Raw Reads By Sample-check_fastqgz_file_contents: &fastqgz_file_contents
  count_lines_to_check: 200_000_000

Trim Reads By Sample-check_fastqgz_file_contents: *fastqgz_file_contents

STAR Alignments By Sample-check_thresholds-Mapped:
  mqc_key: STAR
  stat_string: uniquely_mapped_percent + multimapped_percent
  thresholds:
    - code: YELLOW1
      type: lower
      value: 70
    
    - code: RED1
      type: lower
      value: 50
    
STAR Alignments By Sample-check_thresholds-MultiMapped:
  mqc_key: STAR
  stat_string: multimapped_toomany_percent + multimapped_percent
  thresholds:
    - code: YELLOW1
      type: lower
      value: 30
    
    - code: RED1
      type: lower
      value: 15

RSeQC-check_for_outliers:
  mqc_module: RSeQC
  mqc_plot: Gene Body Coverage
  mqc_keys:
    - _ALL
  thresholds:
    - code: YELLOW1
      stdev_threshold: 2
      middle_fcn: median
    - code: RED1
      stdev_threshold: 4
      middle_fcn: median

RSeQC-check_for_outliers-infer_experiment:
  mqc_module: RSeQC
  mqc_plot: Infer experiment
  mqc_keys:
    - _ALL
  thresholds:
    - code: YELLOW1
      stdev_threshold: 2
      middle_fcn: median
    - code: RED1
      stdev_threshold: 4
      middle_fcn: median

RSeQC-check_for_outliers-inner_distance:
  mqc_module: RSeQC
  mqc_plot: Inner Distance
  mqc_keys:
    - _ALL
  thresholds:
    - code: YELLOW1
      stdev_threshold: 2
      middle_fcn: median
    - code: RED1
      stdev_threshold: 4
      middle_fcn: median

RSeQC-check_for_outliers-read_distribution:
  mqc_module: RSeQC
  mqc_plot: Read Distribution
  mqc_keys:
    - _ALL
  thresholds:
    - code: YELLOW1
      stdev_threshold: 2
      middle_fcn: median
    - code: RED1
      stdev_threshold: 4
      middle_fcn: median

RSeQC-check_strandedness_assessable_from_infer_experiment:
  # refer to the dominant strandedness median percent
  stranded_assessment_range:
    max: 100
    min: 75
  unstranded_assessment_range:
    min: 40
    max: 60
  valid_dominant_strandedness_assessments:
    - Sense (% Tags)
    - Antisense (% Tags)
    # note: Undetermined is an category
    # however, it is not a valid assessment for processing purposes
