# Commands to start on workspace startup
tasks:
  - init: |
          pyenv install miniconda3-4.7.12
          pyenv activate miniconda3-4.7.12
          conda env create -f condaEnv.yaml -p /workspace/dp_tools/.empty/dp_tools
  
  - command: |
             pyenv activate miniconda3-4.7.12
             conda activate /workspace/dp_tools/.empty/dp_tools