name: dp_tools
channels:
   - bioconda
   - conda-forge
   - defaults
dependencies:
   - python=3.10 # required for in-house codebase compatibility
   - pandas
   - samtools
   - isatools
   - multiqc
   - pip

